import { expect, test } from "bun:test";
import { buildWebGLTickContext } from "../src/runtime/create-runtime/render-tick-webgl-context";
import type { WebGLState } from "../src/renderer";
import type { RenderState } from "../src/wasm";

function createIncompleteRenderState(): RenderState {
  return {
    rows: 1,
    cols: 1,
    cellCount: 1,
    codepoints: null,
    contentTags: null,
    wide: null,
    cellFlags: null,
    styleFlags: null,
    linkIds: null,
    fgBytes: null,
    bgBytes: null,
    ulBytes: null,
    ulStyle: null,
    linkOffsets: null,
    linkLengths: null,
    linkBuffer: null,
    graphemeOffset: null,
    graphemeLen: null,
    graphemeBuffer: null,
    selectionStart: null,
    selectionEnd: null,
    cursor: null,
  };
}

test("buildWebGLTickContext does not clear the framebuffer for incomplete render states", () => {
  let clearCalls = 0;
  const gl = {
    FRAMEBUFFER: 1,
    COLOR_BUFFER_BIT: 2,
    viewport() {},
    bindFramebuffer() {},
    clearColor() {},
    clear() {
      clearCalls += 1;
    },
  };

  const state = { gl } as unknown as WebGLState;
  const ctx = buildWebGLTickContext(
    {
      isShaderStagesDirty: () => false,
      rebuildWebGLShaderStages: () => undefined,
      setShaderStagesDirty: () => undefined,
      getCompiledWebGLShaderStages: () => [],
      ensureWebGLStageTargets: () => null,
      canvas: { width: 640, height: 480 } as HTMLCanvasElement,
      defaultBg: [0, 0, 0, 1],
      fontError: null,
      termDebug: null,
      reportDebugText: () => undefined,
      updateGrid: () => undefined,
      getRenderState: () => createIncompleteRenderState(),
      fontState: { font: {} } as never,
      resolveBlendFlags: () => ({ useLinearBlending: false, useLinearCorrection: false }),
      alphaBlending: "native",
      reportTermSize: () => undefined,
      resolveCursorPosition: () => null,
      reportCursor: () => undefined,
      FORCE_CURSOR_BLINK: false,
      CURSOR_BLINK_MS: 530,
      imeInput: null,
      resolveCursorStyle: () => null,
      isFocused: true,
      imeState: { preedit: "", selectionStart: 0, selectionEnd: 0 },
      resolveImeAnchor: () => null,
      wasmExports: null,
      wasmHandle: 0,
      gridState: {
        cellW: 0,
        cellH: 0,
        fontSizePx: 0,
        scale: 1,
        lineHeight: 0,
        baselineOffset: 0,
        yPad: 0,
      },
      updateImePosition: () => undefined,
      buildFontAtlasIfNeeded: () => ({ rebuilt: false, atlas: null, rgba: null }) as never,
      resolveGlyphPixelMode: () => 0,
      atlasBitmapToRGBA: () => new Uint8Array(),
      padAtlasRGBA: () => new Uint8Array(),
      buildAtlas: () => null as never,
      buildGlyphAtlasWithConstraints: () => null as never,
      buildColorEmojiAtlasWithCanvas: () => null as never,
      rasterizeGlyph: () => null as never,
      rasterizeGlyphWithTransform: () => null as never,
      nerdConstraintSignature: () => "",
      ATLAS_PADDING: 0,
      SYMBOL_ATLAS_PADDING: 0,
      SYMBOL_ATLAS_MAX_SIZE: 0,
      PixelMode: {},
      ensureGLInstanceBuffer: () => undefined,
      GLYPH_INSTANCE_FLOATS: 0,
      lastRenderState: null,
      fontHeightUnits: () => 0,
      fontScaleOverride: () => 1,
      FONT_SCALE_OVERRIDES: [],
      getLigatures: () => false,
      getFontHinting: () => false,
      getFontHintTarget: () => "normal",
      isSymbolFont: () => false,
      isColorEmojiFont: () => false,
      fontAdvanceUnits: () => 0,
      shapeClusterWithFont: () => ({ advance: 0, glyphs: [] }),
      fontMaxCellSpan: () => 1,
      clamp: (value: number) => value,
      buildNerdMetrics: () =>
        ({
          cellWidth: 0,
          cellHeight: 0,
          faceWidth: 0,
          faceHeight: 0,
          faceY: 0,
          iconHeight: 0,
          iconHeightSingle: 0,
        }) as never,
      nerdIconScale: 1,
      selectionState: { active: false, dragging: false },
      selectionForRow: () => null,
      getSearchViewportMatches: () => [],
      pushRect: () => undefined,
      pushRectBox: () => undefined,
      selectionBackgroundColor: { kind: "ansi", index: 0 },
      selectionForegroundColor: null,
      searchMatchBackgroundColor: { kind: "ansi", index: 0 },
      searchCurrentMatchBackgroundColor: { kind: "ansi", index: 0 },
      searchMatchTextColor: { kind: "ansi", index: 0 },
      searchCurrentMatchTextColor: { kind: "ansi", index: 0 },
      STYLE_BOLD: 1,
      STYLE_ITALIC: 2,
      STYLE_FAINT: 4,
      STYLE_BLINK: 8,
      STYLE_INVERSE: 16,
      STYLE_INVISIBLE: 32,
      STYLE_STRIKE: 64,
      STYLE_OVERLINE: 128,
      STYLE_UNDERLINE_MASK: 256,
      decodeRGBAWithCache: () => [1, 1, 1, 1],
      brighten: (color: [number, number, number, number]) => color,
      BOLD_BRIGHTEN: 0,
      fade: (color: [number, number, number, number]) => color,
      FAINT_ALPHA: 1,
      linkState: { hoverId: 0 },
      drawUnderlineStyle: () => undefined,
      drawStrikethrough: () => undefined,
      drawOverline: () => undefined,
      KITTY_PLACEHOLDER_CP: 0,
      isSpaceCp: () => false,
      shouldMergeTrailingClusterCodepoint: () => false,
      isBlockElement: () => false,
      drawBlockElement: () => false,
      isBoxDrawing: () => false,
      drawBoxDrawing: () => false,
      isBraille: () => false,
      drawBraille: () => false,
      isPowerline: () => false,
      drawPowerline: () => false,
      pickFontIndexForText: () => 0,
      stylePreferenceFromFlags: () => 0,
      noteColorGlyphText: () => undefined,
      isRenderSymbolLike: () => false,
      resolveSymbolConstraint: () => null,
      isGraphicsElement: () => false,
      glyphWidthUnits: () => 0,
      isAppleSymbolsFont: () => false,
      decodePackedRGBA: () => [1, 1, 1, 1],
      cursorFallback: [1, 1, 1, 1],
      dbgEl: null,
      srgbToLinearColor: (color: [number, number, number, number]) => color,
      webgpuUniforms: new Float32Array(),
      ensureInstanceBuffer: () => undefined,
      GLYPH_INSTANCE_FLOATS_WEBGPU: 0,
      wasm: null,
      collectKittyDrawPlan: () => null,
      resolveKittyWebGPUBindGroup: () => null,
      syncScrollbar: () => undefined,
      scrollbarState: { lastTotal: 0, lastOffset: 0, lastLen: 0 },
      decodePackedRGBAWithCache: () => [1, 1, 1, 1],
      fitTextTailToWidth: (text: string) => ({ text, widthPx: 0, offset: 0 }),
      PREEDIT_BG: [0, 0, 0, 1],
      PREEDIT_UL: [0, 0, 0, 1],
      PREEDIT_ACTIVE_BG: [0, 0, 0, 1],
      PREEDIT_CARET: [0, 0, 0, 1],
      PREEDIT_FG: [1, 1, 1, 1],
      resizeState: { cols: 0, rows: 0, dpr: 1, active: false, lastAt: 0 },
      RESIZE_OVERLAY_HOLD_MS: 0,
      RESIZE_OVERLAY_FADE_MS: 0,
    } as never,
    state,
  );

  expect(ctx).toBeNull();
  expect(clearCalls).toBe(0);
});
